version: '3.3'
services:
    handler:
        build:
          context: .
          dockerfile: linebot.Dockerfile
          cache:
            - alpine
            - mikejhan4455:v1.03-lo
        
        container_name: handler
        image: mikejhan4455/linebot:v1.04-lo

        env_file:
            # - ./env-file/linebot.env
            - ./env-file/obasan-linebot.env

        depends_on:
            - "ngrok-server"

        network_mode: "container:ngrok-server"

    ngrok-server:
        container_name: ngrok-server
        image: "wernight/ngrok"

        env_file:
            - ./env-file/ngrok.env
            - ./env-file/obasan-ngrok.env